version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - npm run build      # produces `dist/`
artifacts:
  base-directory: dist    # <-- this folder gets zipped / where vite writes files
  files:
    - '**/*'